
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Mar 19 2025 09:45:33 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aboutpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutimage!: Elements.AssetsElement;
    public customercount!: Elements.TextElement;
    public propertiescount!: Elements.TextElement;
    public experiencecount!: Elements.TextElement;
    public ourvaluesheading!: Elements.TextElement;
    public ourvaluescontent!: Elements.RichTextElement;
    public ourvaluesitems!: Elements.LinkedItemsElement<ContentItem>;
    public ourachievementsheading!: Elements.TextElement;
    public ourachievementscontent!: Elements.RichTextElement;
    public ourachievementsitems!: Elements.LinkedItemsElement<ContentItem>;
    public processheading!: Elements.TextElement;
    public processcontent!: Elements.RichTextElement;
    public processitems!: Elements.LinkedItemsElement<ContentItem>;
    public whychooseheading!: Elements.TextElement;
    public whychoosecontent!: Elements.RichTextElement;
    public whychooseimage!: Elements.AssetsElement;
    public whychooseitems!: Elements.LinkedItemsElement<ContentItem>;
    public teamheading!: Elements.TextElement;
    public teamcontent!: Elements.RichTextElement;
    public teamitems!: Elements.LinkedItemsElement<ContentItem>;
}
