
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Mar 22 2025 12:00:25 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Contactpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public formheading!: Elements.TextElement;
    public formcontent!: Elements.RichTextElement;
    public formsubmit!: Elements.TextElement;
    public locationheading!: Elements.TextElement;
    public locationcontent!: Elements.RichTextElement;
    public locationembedlink!: Elements.TextElement;
}
