
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Mar 29 2025 13:37:44 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Floorplanitem extends ContentItem {
    public planimage!: Elements.AssetsElement;
    public category!: Elements.TextElement;
    public unittype!: Elements.TextElement;
    public floordetails!: Elements.TextElement;
    public sizes!: Elements.TextElement;
    public type!: Elements.TextElement;
}
