
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Apr 25 2025 12:12:29 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Footer extends ContentItem {
    public address!: Elements.TextElement;
    public phone1!: Elements.TextElement;
    public phone2!: Elements.TextElement;
    public email!: Elements.TextElement;
    public popularsearchitems!: Elements.LinkedItemsElement<ContentItem>;
    public quicklinksitems!: Elements.LinkedItemsElement<ContentItem>;
    public discoveryitems!: Elements.LinkedItemsElement<ContentItem>;
    public facebooklink!: Elements.TextElement;
    public xlink!: Elements.TextElement;
    public instagramlink!: Elements.TextElement;
    public linkedinlink!: Elements.TextElement;
}
