
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Mar 14 2025 10:15:57 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public partneritems!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutitems!: Elements.LinkedItemsElement<ContentItem>;
    public aboutimage!: Elements.AssetsElement;
    public howheading!: Elements.TextElement;
    public howcontent!: Elements.RichTextElement;
    public howitems!: Elements.LinkedItemsElement<ContentItem>;
    public whyheading!: Elements.TextElement;
    public whycontent!: Elements.RichTextElement;
    public whyitems!: Elements.LinkedItemsElement<ContentItem>;
    public explorecitiesheading!: Elements.TextElement;
    public explorecitiescontent!: Elements.RichTextElement;
    public explorecitiesbtnlocale!: Elements.TextElement;
    public explorecitiesbtnlink!: Elements.TextElement;
    public testimonialheading!: Elements.TextElement;
    public testimonialsubheading!: Elements.TextElement;
    public testimonialitems!: Elements.LinkedItemsElement<ContentItem>;
    public blogheading!: Elements.TextElement;
    public blogsubheading!: Elements.TextElement;
    public blogitems!: Elements.LinkedItemsElement<ContentItem>;
}
