
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Mar 15 2025 15:34:14 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Landmarkitem extends ContentItem {
    public name!: Elements.TextElement;
    public distance!: Elements.TextElement;
}
