
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Mar 14 2025 10:15:57 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menu extends ContentItem {
    public logo!: Elements.AssetsElement;
    public phonelabel!: Elements.TextElement;
    public phonenumber!: Elements.TextElement;
    public emaillabel!: Elements.TextElement;
    public email!: Elements.TextElement;
    public address!: Elements.RichTextElement;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
    public linkedin!: Elements.TextElement;
    public facebook!: Elements.TextElement;
    public instagram!: Elements.TextElement;
}
