
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Mar 18 2025 15:37:25 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Paymentscheduleitem extends ContentItem {
    public percentage!: Elements.TextElement;
    public description!: Elements.TextElement;
    public paymenttiming!: Elements.TextElement;
}
