
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Mar 26 2025 10:41:04 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */

export class Paymentplanitem extends ContentItem {
    public name!: Elements.TextElement;
    public percentage!: Elements.TextElement;
    public paymenttiming!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
