
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Mar 18 2025 15:37:25 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Paymentplan extends ContentItem {
    public name!: Elements.TextElement;
    public paymentschedule!: Elements.LinkedItemsElement<ContentItem>;
    public eoi!: Elements.TextElement;
    public resalecondition!: Elements.TextElement;
}
