
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Mar 26 2025 10:41:04 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Projectitem extends ContentItem {
    public name!: Elements.TextElement;
    public price!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public description!: Elements.RichTextElement;
    public developername!: Elements.TextElement;
    public location!: Elements.MultipleChoiceElement;
    public locationembedlink!: Elements.TextElement;
    public nearestlandmark!: Elements.LinkedItemsElement<ContentItem>;
    public propertytype!: Elements.MultipleChoiceElement;
    public propertysize!: Elements.TextElement;
    public buildyear!: Elements.TextElement;
    public featuresheading!: Elements.TextElement;
    public featureitems!: Elements.TextElement;
    public facilitiesheading!: Elements.TextElement;
    public facilitiesitems!: Elements.LinkedItemsElement<ContentItem>;
    public unitsheading!: Elements.TextElement;
    public unitsitems!: Elements.LinkedItemsElement<ContentItem>;
    public paymentplansheading!: Elements.TextElement;
    public paymentplanitems!: Elements.LinkedItemsElement<ContentItem>;
    public bedroomcount!: Elements.TextElement;
    public bathroomcount!: Elements.TextElement;
    public completion!: Elements.TextElement;
    public status!: Elements.TextElement;
    public unittype!: Elements.TextElement;
    public floors!: Elements.TextElement;
    public furnishing!: Elements.TextElement;
    public servicecharge!: Elements.TextElement;
    public readinessprogress!: Elements.TextElement;
}
