
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Sep 11 2025 14:01:58 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Projectitem2025 extends ContentItem {
    public propertyname!: Elements.TextElement;
    public slug!: Elements.UrlSlugElement;
    public pricelabel!: Elements.TextElement;
    public price!: Elements.TextElement;
    public location!: Elements.TextElement;
    public images!: Elements.AssetsElement;
    public overviewheading!: Elements.TextElement;
    public overviewsubheading!: Elements.TextElement;
    public overviewitems!: Elements.LinkedItemsElement<ContentItem>;
    public aboutcontent!: Elements.RichTextElement;
    public amenitiesheading!: Elements.TextElement;
    public amenitiessubheading!: Elements.TextElement;
    public amenities!: Elements.LinkedItemsElement<ContentItem>;
    public downloadbrochurelabel!: Elements.TextElement;
    public downloadbrochurelink!: Elements.TextElement;
    public floorplanheading!: Elements.TextElement;
    public floorplansubheading!: Elements.TextElement;
    public floorplanitems!: Elements.LinkedItemsElement<ContentItem>;
    public downloadfloorplanlabel!: Elements.TextElement;
    public downloadfloorplanlink!: Elements.TextElement;
    public mapheading!: Elements.TextElement;
    public maplink!: Elements.TextElement;
    public nearestlandmarkitems!: Elements.LinkedItemsElement<ContentItem>;
    public youtubevideolink!: Elements.TextElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
