
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri May 30 2025 21:11:08 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Projectitem extends ContentItem {
    public name!: Elements.TextElement;
    public slug!: Elements.UrlSlugElement;
    public price!: Elements.TextElement;
    public developer!: Elements.MultipleChoiceElement;
    public location!: Elements.MultipleChoiceElement;
    public image!: Elements.AssetsElement;
    public propertytype!: Elements.MultipleChoiceElement;
    public propertysize!: Elements.TextElement;
    public downpayment!: Elements.TextElement;
    public duringconstruction!: Elements.TextElement;
    public handover!: Elements.TextElement;
    public posthandover!: Elements.TextElement;
    public completion!: Elements.TextElement;
    public paymentplantype!: Elements.TextElement;
    public description!: Elements.RichTextElement;
    public featuresheading!: Elements.TextElement;
    public featureitems!: Elements.TextElement;
    public locationembedlink!: Elements.TextElement;
    public nearestlandmark!: Elements.RichTextElement;
    public downloadbrochurelink!: Elements.TextElement;
    public downloadfloorplanlink!: Elements.TextElement;
    public floorplanheading!: Elements.TextElement;
    public floorplanitems!: Elements.LinkedItemsElement<ContentItem>;
    public paymentplansheading!: Elements.TextElement;
    public paymentplanitems!: Elements.LinkedItemsElement<ContentItem>;
    public handoverqr!: Elements.MultipleChoiceElement;
    public handoveryr!: Elements.MultipleChoiceElement;
    public unitsheading!: Elements.TextElement;
    public unitsitems!: Elements.LinkedItemsElement<ContentItem>;
    public bedroom!: Elements.MultipleChoiceElement;
    public bathroomcount!: Elements.TextElement;
    public status!: Elements.TextElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    public dldpermitqrimage!: Elements.AssetsElement;
    public dldpermitnumber!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
