
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Mar 14 2025 17:21:32 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Projectpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannercontent!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public projectitems!: Elements.LinkedItemsElement<ContentItem>;
}
