
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Mar 19 2025 09:45:33 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Teamitem extends ContentItem {
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public designation!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public linkedin!: Elements.TextElement;
}
